### PR TITLE
Update tap version to avoid intermittent test failures.

### PR DESCRIPTION
**Pull request by DavidTanner**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Even after #113 was closed, I can still get random errors in route.test.js.  I have tested it over and over, and believe it is caused by the internals of Tap when collecting coverage.  To test the theory I updated tap, and relevant tests, and can no longer repro the timeout.  

I tested using a simple script that called `npx tap` repeatedly until a failure occurred.

### CODE REVIEW

**Review by Uzlopak — CHANGES_REQUESTED** [review]
We must unfortunately wait till BlueOak is OSI approved.

**Review by mcollina — APPROVED** [review]
lgtm as soon as it's osi approved (not long)

**Comment by gurgunday** [comment]
Should there be a next branch?

The workflow change will stop testing for node v14

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
(to land as BlueOak is OSI-approved).

**Comment by DavidTanner** [comment]
@Uzlopak the license has been approved, can this PR be merged now?

**Review by gurgunday — APPROVED** [review]
lgtm

**Review by Uzlopak — APPROVED** [review]

**Pull request merged**
