### PR TITLE
Fix: add ability to change default logo

### PR DESCRIPTION
**Pull request by vserpokryl**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by vserpokryl** [comment]
Fix for https://github.com/fastify/fastify-swagger-ui/issues/92

**Comment by Uzlopak** [comment]
Yeah, hmm. It fixes it for backwards compatibility. But what if someone provides an svg as logo?

**Comment by vserpokryl** [comment]
@Uzlopak 
> Yeah, hmm. It fixes it for backwards compatibility. But what if someone provides an svg as logo?

It's fine, because user always provides content as buffer/string, and then this content serialize to base64

`@fastify/swagger-ui/lib/swagger-initializer.js`
```javascript
const logoBase64 = Buffer.from(opts.logo.content).toString('base64')
const logoData = `data:${opts.logo.type};base64,${logoBase64}`
```

`@fastify/swagger-ui/types/index.d.ts`
```typescript
type FastifySwaggerUILogo = {
  type: string;
  content: string | Buffer;
}
```

**Comment by vserpokryl** [comment]
@Uzlopak the src replacement logic in the img was the same before, nothing has changed here

**Comment by vserpokryl** [comment]
@Uzlopak 
Small example:
```js
import fastify from 'fastify';
import swagger from '@fastify/swagger';
import swaggerUI from '@fastify/swagger-ui';

const app = fastify({ logger: true });

(async () => {
  const response = await fetch('https://www.reshot.com/preview-assets/icons/CZ2NMXUGQ8/code-CZ2NMXUGQ8.svg');
  const content = await response.arrayBuffer();

  app.register(swagger);

  app.register(swaggerUI, {
    routePrefix: '/docs',
    logo: {
      content,
      type: 'image/svg+xml',
    },
  });

  await app.listen({ host: '127.0.0.1', port: 3001 });
})();

```

**Review by gurgunday — APPROVED** [review]
lgtm

**Comment by gurgunday** [comment]
CI using yarn failed

**Comment by Eomm** [comment]
Could we add a test to avoid regression for next swaggerUI bumps?

**Comment by Eomm** [comment]
I was thinking about Playwright if you are willing to try it.
But yeah, we can open a new issue for this

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]
image

merging 👋🏼 yarn

**Pull request merged**
